{% set version = "1.5.0" %}

package:
    name: pyophidia
    version: "{{ version }}"

source:
    url: https://github.com/OphidiaBigData/PyOphidia/archive/v{{ version}}.tar.gz
    sha256: 85c5fcebfb158b0045661c815153df182df3607324b66e63e4c904a71f3fc102

build:
    number: 0
    noarch: python
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - PyOphidia

about:
    home:  http://github.com/OphidiaBigData/PyOphidia
    license:  GPL-3.0
    license_family: GPL
    license_file: LICENSE
    summary: PyOphidia is a Python package for interacting with the Ophidia framework.

extra:
    recipe-maintainers:
        - doutriaux1
        - eldoo
        - minomicetto
        - aledanca
        - sandrofiore
