{% set version = "1.7.0" %}

package:
    name: pyophidia
    version: "{{ version }}"

source:
    url: https://github.com/OphidiaBigData/PyOphidia/archive/v{{ version}}.tar.gz
    sha256: bffc8b5cf40048799ab353a9e0c278e2243308b1a96beeccc096364bd5dea884

build:
    number: 0
    noarch: python
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
        - pip
    run:
        - python

test:
    imports:
        - PyOphidia

about:
    home:  http://github.com/OphidiaBigData/PyOphidia
    license:  GPL-3.0
    license_family: GPL
    license_file: LICENSE
    summary: PyOphidia is a Python package for interacting with the Ophidia framework.

extra:
    recipe-maintainers:
        - doutriaux1
        - eldoo
        - minomicetto
        - aledanca
        - sandrofiore
