travis:
  secure:
    BINSTAR_TOKEN: YBqpuzG01AKvsIutc5FXiLnU3d9CHNuCcYUzx/npodvTdkCfWZjlfv+muBe7dLDus+PTC/66R/n4ry1gT6176vYEp6sIhL9AIPKzU0AaJqtj0XWtEJIlXBywq5WTeUlyb23XoOkub3/7f7VgNK3CbnxILRzq3CglOnPa9iJ5FVbSl8RUU5wcu/6jAcLIAPaCH4SbwfwSAbseqENfJU6sHSI+CfjDIHq1X1xbOSL8mK69wdBFKTJbrg51qafbm6Ivw0WGKl2WYZfvvOweL3/EbWi6se7INXAgW2SooW3DLzZiZjGrgXzY4SfIY4tPoY+7II/sArUCmpaidCDCr4bIgJkfXezg3JuP8vNNGRhZkNuORHWczfL65kejj4HLMLyzOuGDe8V5MAVMRRLrn7QeXGLEJdcQhN2ZDi8cRattXde+5moMNLZYE+X7wCkqwCpKgzcK3A48Eyipy326rnf+Q+rn9iUaC7gJ8zt/mk7bRBwMFrLBx5meFoXoZEnRnGpKr74NnU7fPnnpe5iEA1Xyd4M6lcRS+0HysIqcwC9nqcWhSIXC4oDxGCQgLLIHezVQvzOrGutknAwaswuLgrGrbsNitbLjadDGFvKNr9YaoQ33fMII8UQK1J1QMi2+UWCCcWSbJ7mz39Ln8I3wVELgwZAcNxM+91TFuhcWrbmU4e0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
